// Generated by Haxe 3.4.7
(function ($hx_exports) { "use strict";
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var react_native_api_StyleSheet = require("react-native").StyleSheet;
var Main = function() { };
Main.main = function() {
};
var React_Component = require("react").Component;
var App = $hx_exports["App"] = function(props) {
	React_Component.call(this,props);
	this.state = { scene : 0};
};
App.__super__ = React_Component;
App.prototype = $extend(React_Component.prototype,{
	render: function() {
		var _gthis = this;
		var $goto = function(i) {
			_gthis.setState({ scene : i});
		};
		var _g = this.state.scene;
		switch(_g) {
		case 1:
			var f = $goto;
			var tmp = function() {
				f(0);
			};
			return { "$$typeof" : $$tre, type : scene_Scene1, props : { onPress : tmp}, key : null, ref : null};
		case 2:
			var f1 = $goto;
			var tmp1 = function() {
				f1(0);
			};
			return { "$$typeof" : $$tre, type : scene_Scene2, props : { onPress : tmp1}, key : null, ref : null};
		case 3:
			var f2 = $goto;
			var tmp2 = function() {
				f2(0);
			};
			return { "$$typeof" : $$tre, type : scene_Scene3, props : { onPress : tmp2}, key : null, ref : null};
		default:
			var f3 = $goto;
			var tmp3 = function() {
				f3(1);
			};
			var f4 = $goto;
			var tmp4 = function() {
				f4(2);
			};
			var f5 = $goto;
			var tmp5 = function() {
				f5(3);
			};
			return React.createElement(react_native_component_View,{ style : App.styles.container},React.createElement(react_native_component_Text,{ style : App.styles.text},"Welcome to Haxe + React Native!"),React.createElement(react_native_component_Text,{ style : App.styles.text, onPress : tmp3},"Goto Scene1"),React.createElement(react_native_component_Text,{ style : App.styles.text, onPress : tmp4},"Goto Scene2"),React.createElement(react_native_component_Text,{ style : App.styles.text, onPress : tmp5},"Goto Scene3"));
		}
	}
});
var React = require("react");
var react_native_component_Text = require("react-native").Text;
var react_native_component_View = require("react-native").View;
var scene_Scene1 = function(props,context) {
	React_Component.call(this,props,context);
};
scene_Scene1.__super__ = React_Component;
scene_Scene1.prototype = $extend(React_Component.prototype,{
	render: function() {
		return React.createElement(react_native_component_View,{ style : scene_Scene1.styles.container},React.createElement(react_native_component_Text,{ style : scene_Scene1.styles.text},"This is Scene1"),React.createElement(react_native_component_Text,{ style : scene_Scene1.styles.text, onPress : this.props.onPress},"Back"));
	}
});
var scene_Scene2 = function(props,context) {
	React_Component.call(this,props,context);
};
scene_Scene2.__super__ = React_Component;
scene_Scene2.prototype = $extend(React_Component.prototype,{
	render: function() {
		return React.createElement(react_native_component_View,{ style : scene_Scene2.styles.container},React.createElement(react_native_component_Text,{ style : scene_Scene2.styles.text},"This is Scene2"),React.createElement(react_native_component_Text,{ style : scene_Scene2.styles.text, onPress : this.props.onPress},"Back"));
	}
});
var scene_Scene3 = function(props,context) {
	React_Component.call(this,props,context);
};
scene_Scene3.__super__ = React_Component;
scene_Scene3.prototype = $extend(React_Component.prototype,{
	render: function() {
		return React.createElement(react_native_component_View,{ style : scene_Scene3.styles.container},React.createElement(react_native_component_Text,{ style : scene_Scene3.styles.text},"This is Scene3"),React.createElement(react_native_component_Text,{ style : scene_Scene3.styles.text, onPress : this.props.onPress},"Back"));
	}
});
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
Main.styles = react_native_api_StyleSheet.create({ container : { flex : 1, justifyContent : "center", alignItems : "center", backgroundColor : "#F5FCFF"}, text : { fontSize : 20, textAlign : "center", margin : 10}});
App.styles = Main.styles;
App.displayName = "App";
scene_Scene1.styles = Main.styles;
scene_Scene1.displayName = "Scene1";
scene_Scene2.styles = Main.styles;
scene_Scene2.displayName = "Scene2";
scene_Scene3.styles = Main.styles;
scene_Scene3.displayName = "Scene3";
Main.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);
